name: MinecraftToAIConverter
version: 1.0
main: de.fido.main.Main

commands:
  ask:
    description: If a Villager is near to you, use this command to talk with him.
    usage: /ask <msg>
    permission: minecrafttoaiconverter.ask_command
